on:
  push:
    paths:
      - '**.js'

jobs:
  version_bump:
    runs-on: ubuntu-latest
    steps:
      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording:  '(minor),add,Adds,new'
          major-wording:  '(major),MAJOR'
          patch-wording:  '(patch),(Patch),patch,fixes'     # Providing patch-wording will override commits defaulting to a patch bump.
          rc-wording:     'RELEASE,alpha'
          tag-prefix:     'v'
          commit-message: 'CI: bump version to {{version}} [skip ci]'
          bump-policy:    'all'
